apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mzh1gmma6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mzh1gmma6-java-quarkus-gitops